services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_springboot
      - api_express
    networks:
      - iot_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - iot_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - iot_network

  api_springboot:
    build: ./API1Spring/api
    container_name: api_springboot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iot_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8081:8081
    depends_on:
      - postgres
    networks:
      - iot_network

  api_express:
    build: ./API2Node
    container_name: api_express
    environment:
      - MONGO_URL=mongodb://mongo:27017/iot_db
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - iot_network

  frontend:
    build: ./ReactFrontEnd
    container_name: frontend
    ports:
      - 81:80
    depends_on:
      - api_springboot
      - api_express
    networks:
      - iot_network

volumes:
  mongo_data:
  postgres_data:

networks:
  iot_network:
    driver: bridge
