@URL = http://localhost:8081/animal

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjIyM2UyODk1LTg3ZTAtNDRlYS04ZTczLWVjYzAwODY0MWFhNyIsInVzZXJuYW1lIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNzM0Mzk5MTQ3LCJleHAiOjE3MzQ0MDI3NDcsImlzcyI6IlVURlBSIn0.0LlMoCsqdhli6jfafCdNN1Nkz2vmtOMls5yG0-06yQU
### Obter todas pessoas
GET {{URL}}
Authorization: {{token}}

### Obter uma pessoa pelo ID
GET {{URL}}/2
Authorization: {{token}}

### Criar uma pessoa
POST {{URL}}
Content-Type: application/json

{
  "tagId": "TAGaloizio",
  "name": "Boizinho",
  "breed": "Nelore",
  "age": 3,
  "weight": 450.0,
  "reproductiveStatus": "Macho"
}


### Atualizar uma pessoa
PUT {{URL}}/1
Content-Type: application/json
Authorization: {{token}}

{
  "tagId": "TAG12345",
  "name": "Vaquinha",
  "breed": "Nelore",
  "age": 4,
  "weight": 470.0,
  "reproductiveStatus": "Fêmea - Prenha",
}


### Deletar uma pessoa
DELETE {{URL}}/2
Authorization: {{token}}